CREATE DATABASE LIBRARY;
USE LIBRARY;

CREATE TABLE LECTEUR (
    Id_Lecteur INT NOT NULL AUTO_INCREMENT,
    Nom VARCHAR(50) NOT NULL,
    Prenom VARCHAR(50) NOT NULL,
    Email VARCHAR(50) NOT NULL,
    MDP VARCHAR(255) NOT NULL,
    Frais FLOAT DEFAULT 0.00,
    PRIMARY KEY (Id_Lecteur)
);

CREATE TABLE ETAT (
    Id_Etat INT NOT NULL AUTO_INCREMENT,
    Etat VARCHAR(50) NOT NULL,
    PRIMARY KEY (Id_Etat)
);

INSERT INTO ETAT (Etat) VALUES 
    ('En Retard'),
    ('En Cours');

CREATE TABLE PRET (
    Id_Pret INT NOT NULL AUTO_INCREMENT,
    Id_API TEXT NOT NULL,
    Id_Lecteur INT NOT NULL,
    Date_Emprunt DATE NOT NULL DEFAULT CURDATE(),
    Date_Retour DATE NOT NULL,
    Frais DECIMAL(5,2) DEFAULT 0,
    Id_Etat INT DEFAULT 2,
    PRIMARY KEY (Id_Pret),
    FOREIGN KEY (Id_Lecteur) REFERENCES LECTEUR(Id_Lecteur) ON DELETE CASCADE,
    FOREIGN KEY (Id_Etat) REFERENCES ETAT(Id_Etat)
);

CREATE TABLE FAVORIS (
    Id_Fav INT NOT NULL AUTO_INCREMENT,
    Id_Lecteur INT NOT NULL,
    Id_API INT NOT NULL,
    PRIMARY KEY (Id_Fav),
    FOREIGN KEY (Id_Lecteur) REFERENCES LECTEUR(Id_Lecteur) ON DELETE CASCADE,
);

